name: フィードバック
description: サービスへのフィードバックや改善提案
title: "[Feedback] "
labels: ["feedback"]
body:
  - type: markdown
    attributes:
      value: |
        該当する項目のみ入力してください。全て任意項目です。
  - type: textarea
    id: content
    attributes:
      label: フィードバック内容
      description: サービスに対するご意見・ご感想をお聞かせください
    validations:
      required: false
  - type: input
    id: url
    attributes:
      label: 対象ページURL
      description: フィードバックに関連するページがあればURLを記載してください
      placeholder: https://...
    validations:
      required: false
  - type: textarea
    id: improvement
    attributes:
      label: 改善案
      description: 具体的な改善案があればお聞かせください
    validations:
      required: false
