import { Member } from "../types/member";

export const members: Member[] = [
  {
    id: 1,
    name: "中嶌 竜士朗",
    role: "会長",
    department: "理工学部",
    year: "2年",
    bio: "プログラミングサークルLumosの代表を務めています。ウェブ開発とAIに興味があり、卒業後はIT企業でのキャリアを目指しています。趣味は読書とバスケットボールです。",
    skills: ["JavaScript", "React", "Python", "TensorFlow"],
    image: "/placeholder.svg?height=400&width=400",
    social: {
      twitter: "https://twitter.com/satotaro",
      github: "https://github.com/satotaro",
      linkedin: "https://linkedin.com/in/satotaro",
      website: "https://satotaro.dev",
    },
  },
  {
    id: 2,
    name: "野田 タオ",
    role: "副会長",
    department: "理工学部",
    year: "3年",
    bio: "副代表として、主にイベント企画と運営を担当しています。プログラミングは大学から始めましたが、今ではフロントエンド開発が得意です。趣味は旅行と写真撮影です。",
    skills: ["HTML/CSS", "JavaScript", "Vue.js", "UI/UXデザイン"],
    image: "/placeholder.svg?height=400&width=400",
    social: {
      twitter: "https://twitter.com/suzukihanako",
      github: "https://github.com/suzukihanako",
    },
  },
  {
    id: 3,
    name: "森 悠華",
    role: "副会長",
    department: "経済学部",
    year: "2年",
    bio: "技術リーダーとして、勉強会のカリキュラム作成やメンバーの技術サポートを行っています。バックエンド開発とインフラが得意分野です。趣味は登山とギター演奏です。",
    skills: ["Java", "Spring Boot", "AWS", "Docker", "Kubernetes"],
    image: "/placeholder.svg?height=400&width=400",
    social: {
      github: "https://github.com/tanakakenta",
      linkedin: "https://linkedin.com/in/tanakakenta",
    },
  },
  {
    id: 4,
    name: "美浪 佳怜",
    role: "会計",
    department: "経済学部",
    year: "2年",
    bio: "サークルのデザイン全般を担当しています。ウェブデザインとUI/UXに興味があり、独学で勉強しています。趣味はイラスト制作と音楽鑑賞です。",
    skills: ["Figma", "Adobe XD", "Illustrator", "HTML/CSS"],
    image: "/placeholder.svg?height=400&width=400",
    social: {
      twitter: "https://twitter.com/yamadamisaki",
      website: "https://yamadamisaki.design",
    },
  },
  {
    id: 5,
    name: "武村駿汰",
    role: "広報",
    department: "理工学部",
    year: "2年",
    bio: "サークルの会計を担当しています。データ分析とビジネスに興味があり、将来はデータサイエンティストを目指しています。趣味はサッカーと料理です。",
    skills: ["Python", "R", "SQL", "データ分析"],
    image: "/placeholder.svg?height=400&width=400",
    social: {
      github: "https://github.com/itodaisuke",
      linkedin: "https://linkedin.com/in/itodaisuke",
    },
  },
  {
    id: 6,
    name: "田和 宏平",
    role: "メンバー",
    department: "理工学部",
    year: "2年",
    bio: "広報担当として、SNSの運用やイベントの告知を行っています。マーケティングとコンテンツ制作に興味があります。趣味は映画鑑賞とカフェ巡りです。",
    skills: ["SNS運用", "コンテンツ制作", "HTML/CSS", "WordPress"],
    image: "/placeholder.svg?height=400&width=400",
    social: {
      twitter: "https://twitter.com/nakamurayuu",
      website: "https://nakamurayuu.com",
    },
  },
  {
    id: 7,
    name: "吉田 楓音",
    role: "メンバー",
    department: "教育学部",
    year: "2年",
    bio: "1年生ながらプログラミングの経験が豊富で、特にモバイルアプリ開発に興味があります。高校時代に独学でアプリを開発した経験があります。趣味はゲーム開発と読書です。",
    skills: ["Swift", "Kotlin", "Flutter", "Firebase"],
    image: "/placeholder.svg?height=400&width=400",
    social: {
      github: "https://github.com/kobayashitakuya",
      twitter: "https://twitter.com/kobayashitakuya",
    },
  },
  {
    id: 8,
    name: "西海来",
    role: "メンバー",
    department: "理工学部",
    year: "2年",
    bio: "プログラミング初心者ですが、教育とテクノロジーの融合に興味があり入会しました。将来は教育現場でのICT活用を推進したいと考えています。趣味はピアノと絵本制作です。",
    skills: ["HTML/CSS", "Scratch", "教育工学"],
    image: "/placeholder.svg?height=400&width=400",
    social: {
      twitter: "https://twitter.com/katosakura",
    },
  },
  {
    id: 9,
    name: "谷口 友都",
    role: "メンバー",
    department: "経済学部",
    year: "2年",
    bio: "プログラミング初心者ですが、教育とテクノロジーの融合に興味があり入会しました。将来は教育現場でのICT活用を推進したいと考えています。趣味はピアノと絵本制作です。",
    skills: ["HTML/CSS", "Scratch", "教育工学"],
    image: "/placeholder.svg?height=400&width=400",
    social: {
      twitter: "https://twitter.com/katosakura",
    },
  },
]
