// ニュース記事のデータ
export const newsArticles = [
  {
    id: 9,
    date: "2025年12月11日",
    title: "はじプロ最終発表会",
    summary: "はじめてのプロダクト開発ゼミの最終発表会がありました。",
    image: "https://storage.googleapis.com/lumos-web-profile-data/hajipro.jpg",
    category: "プロジェクト",
  },
  {
    id: 8,
    date: "2026年3月2日",
    title: "ウィークリーmini-LT開始",
    summary:
      "毎週オンラインでのプログラミング成果共有会mini-LTが発足しました。",
    image: "/assets/mini-lt.png",
    category: "プロジェクト",
  },
  {
    id: 4,
    date: "2025年10月31日",
    title: "クレープ屋 Crepe++",
    summary: "常盤祭にてクレープ屋を出店しました。",
    image: "/assets/Crepe.png",
    category: "イベント",
  },
  {
    id: 5,
    date: "2025年10月23日",
    title: "ピザパーティー",
    summary: "サークルメンバーでピザパーティーを開催しました。",
    image: "/assets/pizza.png",
    category: "イベント",
  },
  {
    id: 6,
    date: "2025年7月10日",
    title: "LT会",
    summary: "個人の成果を発表するLT会を開催しました。",
    image: "/assets/LT_1.png",
    category: "プロジェクト",
  },
  {
    id: 7,
    date: "2025年6月17日",
    title: "ドーナツパーティー",
    summary: "サークルメンバーでミスドのドーナツを食べました。",
    image: "/assets/donut.png",
    category: "イベント",
  },

  {
    id: 1,
    date: "2025年5月24日",
    title: "確定大新歓BBQ",
    summary: "5月24日に確定大新歓としてBBQを行いました。",
    image: "/assets/BBQ.jpg",
    category: "イベント",
  },
  {
    id: 2,
    date: "2025年5月21-23日",
    title: "初学者向けプログラミング学習会",
    summary: "21-23日に3日連続の言語学習会をオンライン開催しました。",
    image: "/assets/C-program.png",
    category: "プロジェクト",
  },
  {
    id: 3,
    date: "2025年4月中",
    title: "新入生歓迎イベント",
    summary: "4月中に新入生向けの複数のイベントを開催しました。",
    image: "/assets/shinkan.jpg",
    category: "イベント",
  },
];
